# Generated by Django 3.1.2 on 2020-10-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_published',
            new_name='dt_published',
        ),
    ]
